void TestDispatch(int count) {
	std::cout << "Testing " << name << std::endl;
	std::chrono::high_resolution_clock clock;
	auto before = clock.now();
	for(int i = 0; i < count; ++i) {
		Dispatch("POST /extensions/clientId/auth/secret\r");
		Dispatch("GET /extensions/clientId/auth/secret\r");
		Dispatch("DELETE /extensions/clientId/auth/secret\r");
		Dispatch("GET /extensions/clientId/live_activated_channels\r");
		Dispatch("PUT /extensions/clientId/version/required_configuration\r");
		Dispatch("PUT /extensions/clientId/configurations\r");
		Dispatch("GET /extensions/clientId/configurations/channels/channelId\r");
		Dispatch("GET /extensions/clientId/configurations/segments/broadcaster\r");
		Dispatch("GET /extensions/clientId/configurations/segments/developer\r");
		Dispatch("GET /extensions/clientId/configurations/segments/global\r");
		Dispatch("POST /extensions/message/channelId\r");
		Dispatch("POST /extensions/message/all\r");
		Dispatch("POST /extensions/clientId/version/channels/channelId/chat\r");
		Dispatch("GET /helix/analytics/extensions\r");
		Dispatch("GET /helix/analytics/games\r");
		Dispatch("GET /helix/bits/leaderboard\r");
		Dispatch("POST /helix/clips\r");
		Dispatch("GET /helix/clips\r");
		Dispatch("POST /helix/entitlements/upload\r");
		Dispatch("GET /helix/entitlements/codes\r");
		Dispatch("POST /helix/entitlements/codes\r");
		Dispatch("GET /helix/games/top\r");
		Dispatch("GET /helix/games\r");
		Dispatch("GET /helix/streams\r");
		Dispatch("GET /helix/streams/metadata\r");
		Dispatch("POST /helix/streams/markers\r");
		Dispatch("GET /helix/streams/markers\r");
		Dispatch("GET /helix/users\r");
		Dispatch("GET /helix/users/follows\r");
		Dispatch("PUT /helix/users\r");
		Dispatch("GET /helix/users/extensions/list\r");
		Dispatch("GET /helix/users/extensions\r");
		Dispatch("PUT /helix/users/extensions\r");
		Dispatch("GET /helix/videos\r");
		Dispatch("GET /helix/webhooks/subscriptions\r");
	}
	auto after = clock.now();
	std::chrono::duration<double> duration = after - before;
	std::cout << "Duration:  " << duration.count() << std::endl;
	std::cout << "DELETE_extensions__clientId_auth_secret_count:  " << DELETE_extensions__clientId_auth_secret_count << std::endl;
	std::cout << "GET_extensions__clientId_auth_secret_count:  " << GET_extensions__clientId_auth_secret_count << std::endl;
	std::cout << "GET_extensions__clientId_configurations_channels__channelId_count:  " << GET_extensions__clientId_configurations_channels__channelId_count << std::endl;
	std::cout << "GET_extensions__clientId_configurations_segments_broadcaster_count:  " << GET_extensions__clientId_configurations_segments_broadcaster_count << std::endl;
	std::cout << "GET_extensions__clientId_configurations_segments_developer_count:  " << GET_extensions__clientId_configurations_segments_developer_count << std::endl;
	std::cout << "GET_extensions__clientId_configurations_segments_global_count:  " << GET_extensions__clientId_configurations_segments_global_count << std::endl;
	std::cout << "GET_extensions__clientId_live_activated_channels_count:  " << GET_extensions__clientId_live_activated_channels_count << std::endl;
	std::cout << "GET_helix_analytics_extensions_count:  " << GET_helix_analytics_extensions_count << std::endl;
	std::cout << "GET_helix_analytics_games_count:  " << GET_helix_analytics_games_count << std::endl;
	std::cout << "GET_helix_bits_leaderboard_count:  " << GET_helix_bits_leaderboard_count << std::endl;
	std::cout << "GET_helix_clips_count:  " << GET_helix_clips_count << std::endl;
	std::cout << "GET_helix_entitlements_codes_count:  " << GET_helix_entitlements_codes_count << std::endl;
	std::cout << "GET_helix_games_top_count:  " << GET_helix_games_top_count << std::endl;
	std::cout << "GET_helix_games_count:  " << GET_helix_games_count << std::endl;
	std::cout << "GET_helix_streams_markers_count:  " << GET_helix_streams_markers_count << std::endl;
	std::cout << "GET_helix_streams_metadata_count:  " << GET_helix_streams_metadata_count << std::endl;
	std::cout << "GET_helix_streams_count:  " << GET_helix_streams_count << std::endl;
	std::cout << "GET_helix_users_extensions_list_count:  " << GET_helix_users_extensions_list_count << std::endl;
	std::cout << "GET_helix_users_extensions_count:  " << GET_helix_users_extensions_count << std::endl;
	std::cout << "GET_helix_users_follows_count:  " << GET_helix_users_follows_count << std::endl;
	std::cout << "GET_helix_users_count:  " << GET_helix_users_count << std::endl;
	std::cout << "GET_helix_videos_count:  " << GET_helix_videos_count << std::endl;
	std::cout << "GET_helix_webhooks_subscriptions_count:  " << GET_helix_webhooks_subscriptions_count << std::endl;
	std::cout << "POST_extensions__clientId__version_channels__channelId_chat_count:  " << POST_extensions__clientId__version_channels__channelId_chat_count << std::endl;
	std::cout << "POST_extensions__clientId_auth_secret_count:  " << POST_extensions__clientId_auth_secret_count << std::endl;
	std::cout << "POST_extensions_message__channelId_count:  " << POST_extensions_message__channelId_count << std::endl;
	std::cout << "POST_extensions_message_all_count:  " << POST_extensions_message_all_count << std::endl;
	std::cout << "POST_helix_clips_count:  " << POST_helix_clips_count << std::endl;
	std::cout << "POST_helix_entitlements_codes_count:  " << POST_helix_entitlements_codes_count << std::endl;
	std::cout << "POST_helix_entitlements_upload_count:  " << POST_helix_entitlements_upload_count << std::endl;
	std::cout << "POST_helix_streams_markers_count:  " << POST_helix_streams_markers_count << std::endl;
	std::cout << "PUT_extensions__clientId__version_required_configuration_count:  " << PUT_extensions__clientId__version_required_configuration_count << std::endl;
	std::cout << "PUT_extensions__clientId_configurations_count:  " << PUT_extensions__clientId_configurations_count << std::endl;
	std::cout << "PUT_helix_users_extensions_count:  " << PUT_helix_users_extensions_count << std::endl;
	std::cout << "PUT_helix_users_count:  " << PUT_helix_users_count << std::endl;
}
